# Generated by Django 3.1.11 on 2021-09-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productapplicationvideos',
            name='slug',
            field=models.SlugField(default='tw1aejfxzuskweiuqvgq', verbose_name='Product Video Slug'),
        ),
        migrations.AlterField(
            model_name='productapplicationvideos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
