# Generated by Django 3.1.11 on 2021-12-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_videos', '0004_auto_20211220_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productapplicationvideos',
            name='slug',
            field=models.SlugField(default='rylbpjdlyshdqmtx8gvf', verbose_name='Product Video Slug'),
        ),
    ]
