# Generated by Django 3.1.11 on 2021-12-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_videos', '0005_auto_20211220_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productapplicationvideos',
            name='slug',
            field=models.SlugField(default='jpvu04iy1edf1aszr5c7', verbose_name='Product Video Slug'),
        ),
    ]
