# Generated by Django 4.0 on 2022-01-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_videos', '0008_auto_20211220_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productapplicationvideos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productapplicationvideos',
            name='slug',
            field=models.SlugField(default='asxaww7fvxbdce5yyptb', verbose_name='Product Video Slug'),
        ),
    ]
