# Generated by Django 4.0 on 2022-01-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_videos', '0017_alter_productapplicationvideos_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productapplicationvideos',
            name='slug',
            field=models.SlugField(default='lpmsfmc3e24m8soxnqxj', verbose_name='Product Video Slug'),
        ),
    ]
