# Generated by Django 4.0.1 on 2022-02-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_videos', '0020_alter_productapplicationvideos_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productapplicationvideos',
            name='slug',
            field=models.SlugField(default='i5dxy7hknjfqymrumk0y', verbose_name='Product Video Slug'),
        ),
    ]
