# Generated by Django 3.2.5 on 2021-07-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='j4vpu9', verbose_name='Product Slug'),
        ),
    ]
