# Generated by Django 3.1.11 on 2021-12-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20211220_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='arabic_name',
            field=models.CharField(max_length=120, null=True, verbose_name='Category Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='8zgelljuovdso3w8ojlb', verbose_name='Product Slug'),
        ),
    ]
