# Generated by Django 4.0 on 2022-01-04 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_user_slug'),
        ('orders', '0003_alter_cart_order_alter_cart_product_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.user'),
            preserve_default=False,
        ),
    ]
