# Generated by Django 4.0 on 2022-01-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_slug'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='order',
        #     name='slug',
        #     field=models.SlugField(default='order-88bosdify67', unique=True, verbose_name='Token Slug'),
        # ),
    ]
