# Generated by Django 4.0.1 on 2022-02-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='order-8af62hr5u-141015-2022-02-01', verbose_name='Token Slug'),
        ),
    ]
