# Generated by Django 4.0 on 2022-02-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_order_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='order-fl1rp197o-103957-2022-02-10', verbose_name='Token Slug'),
        ),
    ]
