# Generated by Django 4.0.2 on 2022-02-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_order_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='order-5ad9ch00t-102249-2022-02-12', verbose_name='Token Slug'),
        ),
    ]
