# Generated by Django 4.0.2 on 2022-02-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_order_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='order-qu7053osb-092826-2022-02-13', verbose_name='Token Slug'),
        ),
    ]
