# Generated by Django 3.2.4 on 2021-07-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210726_1056'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='user',
        #     old_name='city_f',
        #     new_name='city_id',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='city',
        # ),
        # migrations.AlterField(
        #     model_name='contactus',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
    ]
