# Generated by Django 3.2.4 on 2021-07-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_contactus_user'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='city_id_id',
        # ),
    ]
