# Generated by Django 3.2.4 on 2021-08-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210802_0919'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='working',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='working_field',
        # ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='7sgbdxwccmtwkltpslvi', verbose_name='User Slug'),
        ),
    ]
