# Generated by Django 3.2.4 on 2021-08-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210811_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='u5vv9qafizeewfpf735k', verbose_name='User Slug'),
        ),
    ]
