# Generated by Django 3.2.4 on 2021-08-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210815_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='vvdxcqkwdai2v7oowhcl', verbose_name='User Slug'),
        ),
    ]
