# Generated by Django 4.0 on 2022-01-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='7qxxsfunwgrgkyyq11dm', verbose_name='User Slug'),
        ),
    ]
