# Generated by Django 4.0.1 on 2022-02-01 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jop_type', '0005_alter_joptype_slug'),
        ('accounts', '0041_alter_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jop_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jop_type.joptype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='o4bddekimeekrqj9lgcs', verbose_name='User Slug'),
        ),
    ]
