# Generated by Django 4.0.1 on 2022-02-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_user_jop_type_alter_user_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='jop_type',
            new_name='job_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='5tnv8q3iq7s9ytptiiwg', verbose_name='User Slug'),
        ),
    ]
