# Generated by Django 4.0.1 on 2022-02-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='ynexkjj9mrzrlbjqo5ig', verbose_name='User Slug'),
        ),
    ]
