# Generated by Django 4.0.1 on 2022-02-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='k7bjgupm7vuhywv4jg4b', verbose_name='User Slug'),
        ),
    ]
