# Generated by Django 4.0.1 on 2022-02-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='mzt7djzowkg29hgnvls4', verbose_name='User Slug'),
        ),
    ]
