# Generated by Django 4.0 on 2022-02-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='l189ckusua7hriznigqs', verbose_name='User Slug'),
        ),
    ]
