# Generated by Django 4.0 on 2022-02-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='xmgszugnceabfzuywgk9', verbose_name='User Slug'),
        ),
    ]
