# Generated by Django 4.0.2 on 2022-02-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='iequmfd5mvftienmotla', verbose_name='User Slug'),
        ),
    ]
