# Generated by Django 3.2.4 on 2021-08-02 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_alter_supplier_slug'),
        ('category', '0004_alter_category_slug'),
        ('product', '0011_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category', verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='1btvnmiphuhndazvjcns', verbose_name='Product Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplier', verbose_name='Supplier Name'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productvideos',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='similarproduct',
            name='original_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Original Product'),
        ),
        migrations.AlterField(
            model_name='similarproduct',
            name='similar_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar_product', to='product.product', verbose_name='Similar Product'),
        ),
    ]
