# Generated by Django 3.2.4 on 2021-08-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvideos',
            name='video',
        ),
        # migrations.AddField(
        #     model_name='productvideos',
        #     name='application_video',
        #     field=models.FileField(default='', upload_to='product_videos', verbose_name='Application Video'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='cv71ity51v8ouakwlj9c', verbose_name='Product Slug'),
        ),
    ]
