# Generated by Django 3.2.4 on 2021-08-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210823_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvideos',
            name='video',
            field=models.FileField(default='', upload_to='product_videos', verbose_name='Application Video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='h3l6rhyeetxvyc8zc0z7', verbose_name='Product Slug'),
        ),
    ]
