# Generated by Django 3.2.4 on 2021-08-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvideos',
            name='video',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='lmgucb4smz2upxuczqif', verbose_name='Product Slug'),
        ),
    ]
