# Generated by Django 3.2.4 on 2021-08-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20210824_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.URLField(default='', verbose_name='Product Video Url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='k3xjky962uj3v9gcjsey', verbose_name='Product Slug'),
        ),
    ]
