# Generated by Django 3.1.11 on 2021-09-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20210905_1525'),
        # ('product', '0014_auto_20210819_1708'),
    ]

    operations = [
    ]
