# Generated by Django 3.1.11 on 2021-09-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20210913_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='svlbbprgjtb2hcq2rpix', verbose_name='Product Slug'),
        ),
    ]
