# Generated by Django 3.1.11 on 2021-12-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20211220_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arabic_description',
            field=models.TextField(blank=True, null=True, verbose_name='Product Description(Arabic)'),
        ),
        migrations.AddField(
            model_name='product',
            name='arabic_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Product Name(Arabic)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='jigddc2lhtgovprit3hd', verbose_name='Product Slug'),
        ),
    ]
