# Generated by Django 4.0 on 2022-01-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='sy93d8x6kdmgm6tylpkh', verbose_name='Product Slug'),
        ),
    ]
