# Generated by Django 4.0.1 on 2022-02-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='sebgzfp05bmwrbbzd2nn', verbose_name='Product Slug'),
        ),
    ]
