# Generated by Django 4.0 on 2022-02-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0062_alter_product_price_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='wq9t52djqa4b1p8wgeg1', verbose_name='Product Slug'),
        ),
    ]
