# Generated by Django 4.0.2 on 2022-02-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0065_alter_product_price_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='ybynr2xg37lkrm6bvzqq', verbose_name='Product Slug'),
        ),
    ]
