# Generated by Django 4.0.2 on 2022-02-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='5haxvcf1bvgp2fuax4xv', verbose_name='Product Slug'),
        ),
    ]
