# Generated by Django 4.0.2 on 2022-02-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0068_alter_product_discount_percentage_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='rrouobdknufj4oaydjee', verbose_name='Product Slug'),
        ),
    ]
