# Generated by Django 4.0 on 2022-02-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0069_alter_product_discount_percentage_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='ekdkeguvisgfke5rfg7i', verbose_name='Product Slug'),
        ),
    ]
