# Generated by Django 3.2.4 on 2021-06-27 12:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brochures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Document Name')),
                ('image', models.ImageField(upload_to='document_field', verbose_name='Document Image')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Product Image')),
                ('category', models.CharField(max_length=150, verbose_name='Product Category')),
                ('product_file', models.FileField(blank=True, null=True, upload_to='product_files/', verbose_name='Product File')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Project Name')),
                ('category', models.CharField(max_length=100, verbose_name='Product Category')),
                ('image', models.ImageField(upload_to='project_images', verbose_name='Project Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Project Description')),
            ],
        ),
        migrations.CreateModel(
            name='SellingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Sale Point Name')),
                ('image', models.ImageField(upload_to='sale_point_image', verbose_name='Sale Point Image')),
                ('location', models.CharField(max_length=200, verbose_name='Sale Point Location')),
                ('address', models.CharField(max_length=250, verbose_name='Sale Point Address')),
            ],
        ),
        migrations.CreateModel(
            name='SellingPointsContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_phone', models.CharField(max_length=20, verbose_name='Sale Point Primary Phone')),
                ('secondary_phone', models.CharField(max_length=20, verbose_name='Sale Point Secondary Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Supplier Name')),
                ('image', models.ImageField(upload_to='', verbose_name='Supplier Image')),
            ],
        ),
        migrations.CreateModel(
            name='SimilarProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniseal.product', verbose_name='Original Product')),
                ('similar_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_product', to='uniseal.product', verbose_name='Similar Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVedios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(verbose_name='Project Video Url')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniseal.project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images', verbose_name='Project Image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniseal.project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVedios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(verbose_name='Product Video Url')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniseal.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='Product Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniseal.product', verbose_name='Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniseal.supplier', verbose_name='Supplier Name'),
        ),
    ]
