# Generated by Django 3.2.4 on 2021-06-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniseal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVedios',
            new_name='ProductVideos',
        ),
        migrations.RenameModel(
            old_name='ProjectVedios',
            new_name='ProjectVideos',
        ),
    ]
