# Generated by Django 3.2.3 on 2021-06-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniseal', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='supplier_name',
            new_name='supplier',
        ),
    ]
