# Generated by Django 3.2.3 on 2021-06-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniseal', '0006_auto_20210628_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brochures',
            name='image',
        ),
        migrations.RemoveField(
            model_name='brochures',
            name='name',
        ),
        migrations.AddField(
            model_name='brochures',
            name='attachment',
            field=models.FileField(default='', upload_to='document_field', verbose_name='Document Attachment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brochures',
            name='title',
            field=models.CharField(default='', max_length=120, verbose_name='Document Title'),
            preserve_default=False,
        ),
    ]
