# Generated by Django 3.2.3 on 2021-06-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniseal', '0007_auto_20210628_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
