# Generated by Django 3.2.4 on 2021-07-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_date',
            field=models.DateField(auto_now=True, verbose_name='Added Date'),
        ),
    ]
