# Generated by Django 3.2.4 on 2021-07-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_slug'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='product',
        #     name='slug',
        #     field=models.SlugField(default='f2vely'),
        # ),
    ]
