# Generated by Django 3.2.4 on 2021-07-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_slug'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='product',
        #     name='slug',
        #     field=models.SlugField(default='rwifog'),
        # ),
    ]
