# Generated by Django 3.2.5 on 2021-08-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_slug'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='productvideos',
        #     name='application_video',
        #     field=models.FileField(default='', upload_to='product_videos', verbose_name='Application Video'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='product',
        #     name='slug',
        #     field=models.SlugField(default='ziugk9uqyddmjo789nkr', verbose_name='Product Slug'),
        # ),
    ]
