# Generated by Django 3.2.4 on 2021-08-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20210823_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='pvlfxvf8ndqw2cddwzwk', verbose_name='Product Slug'),
        ),
        # migrations.RemoveField(
        #     model_name='productvideos',
        #     name='application_video',
        # ),
    ]
