# Generated by Django 3.2.4 on 2021-08-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20210824_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='1s4urddsmfgebvp7bdlk', verbose_name='Product Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Product Video Url'),
        ),
    ]
