# Generated by Django 3.2.4 on 2021-08-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20210824_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='c31ix2vkfcrdyhpangup', verbose_name='Product Slug'),
        ),
    ]
