# Generated by Django 3.2.5 on 2021-08-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210819_1708'),
        ('product', '0020_alter_product_slug'),
    ]

    operations = [
    ]
