# Generated by Django 3.2.5 on 2021-09-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210819_1708'),
        ('product', '0021_merge_0014_auto_20210819_1708_0020_alter_product_slug'),
    ]

    operations = [
    ]
