# Generated by Django 4.0 on 2022-01-04 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210819_1708'),
        ('product', '0035_alter_product_slug'),
    ]

    operations = [
    ]
