# Generated by Django 4.0 on 2022-01-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_merge_0014_auto_20210819_1708_0035_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='esrilugs0mesj3gwiuxe', verbose_name='Product Slug'),
        ),
    ]
