# Generated by Django 3.1.11 on 2021-09-19 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20210919_0831'),
        ('application_videos', '0002_auto_20210918_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productapplicationvideos',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productapplicationvideos',
            name='slug',
            field=models.SlugField(default='vrvhqxhshuycnnc8keh5', verbose_name='Product Video Slug'),
        ),
    ]
