# Generated by Django 3.1.11 on 2021-12-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_videos', '0003_auto_20210919_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productapplicationvideos',
            name='slug',
            field=models.SlugField(default='4xe1mpo5gijolespucfh', verbose_name='Product Video Slug'),
        ),
    ]
