# Generated by Django 4.0 on 2022-01-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_videos', '0009_alter_productapplicationvideos_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productapplicationvideos',
            name='slug',
            field=models.SlugField(default='1bi8snoqgojodoaugjoz', verbose_name='Product Video Slug'),
        ),
    ]
