# Generated by Django 4.0 on 2022-01-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_videos', '0018_alter_productapplicationvideos_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productapplicationvideos',
            name='slug',
            field=models.SlugField(default='zmho28qjmyxfpdb1wfjr', verbose_name='Product Video Slug'),
        ),
    ]
