# Generated by Django 4.0 on 2022-01-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingPoint', '0014_alter_sellingpoint_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingpoint',
            name='slug',
            field=models.SlugField(default='9yn6lmrtxogza0vdo9ec', verbose_name='Selling Point Slug'),
        ),
    ]
