# Generated by Django 4.0.1 on 2022-02-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingPoint', '0025_alter_sellingpoint_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingpoint',
            name='slug',
            field=models.SlugField(default='2l9fli2bmkuk2aayy4tp', verbose_name='Selling Point Slug'),
        ),
    ]
