# Generated by Django 4.0.1 on 2022-02-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingPoint', '0031_alter_sellingpoint_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingpoint',
            name='slug',
            field=models.SlugField(default='rrph5pja1bdejebehrpp', verbose_name='Selling Point Slug'),
        ),
    ]
