# Generated by Django 4.0 on 2022-02-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingPoint', '0037_alter_sellingpoint_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingpoint',
            name='slug',
            field=models.SlugField(default='p73usvxt2t8jle938t2t', verbose_name='Selling Point Slug'),
        ),
    ]
