# Generated by Django 4.0.2 on 2022-02-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingPoint', '0038_alter_sellingpoint_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingpoint',
            name='slug',
            field=models.SlugField(default='gk0kbx0ln9hjx2zvv1nk', verbose_name='Selling Point Slug'),
        ),
    ]
