# Generated by Django 3.1.11 on 2021-07-18 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Solution Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Solution Description')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(verbose_name='Solution Video Url')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.solution', verbose_name='Solution')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='solution_images', verbose_name='Solution Image')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.solution', verbose_name='Solution')),
            ],
        ),
    ]
