# Generated by Django 3.1.11 on 2021-12-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0004_auto_20211220_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='arabic_title',
            field=models.CharField(max_length=150, null=True, verbose_name='Solution Title(Arabic)'),
        ),
    ]
