# Generated by Django 3.2.4 on 2021-09-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_updates', '0002_auto_20210819_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryupdates',
            name='image_link',
            field=models.URLField(default='', verbose_name='Image Link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industryupdates',
            name='slug',
            field=models.SlugField(default='wctarxyhbrjs3pt3okmo', verbose_name='Industry Slug'),
        ),
    ]
