# Generated by Django 3.2.5 on 2021-09-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_updates', '0005_auto_20210904_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industryupdates',
            name='link',
        ),
        migrations.AlterField(
            model_name='industryupdates',
            name='slug',
            field=models.SlugField(default='bojsjluwail3teamsjjo', verbose_name='Industry Slug'),
        ),
    ]
