# Generated by Django 3.1.11 on 2021-12-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_updates', '0009_auto_20211220_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryupdates',
            name='arabic_details',
            field=models.TextField(null=True, verbose_name='Details(Arabic)'),
        ),
        migrations.AddField(
            model_name='industryupdates',
            name='arabic_headline',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title(Arabic)'),
        ),
        migrations.AlterField(
            model_name='industryupdates',
            name='slug',
            field=models.SlugField(default='17raipgfv8gc45w2cped', verbose_name='Industry Slug'),
        ),
    ]
