# Generated by Django 4.0.1 on 2022-02-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joptype',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
    ]
