# Generated by Django 4.0.1 on 2022-02-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop_type', '0003_joptype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joptype',
            name='slug',
            field=models.SlugField(default='fmczpxykei2jf0bjvzsl', verbose_name='Jop Type Slug'),
        ),
    ]
