# Generated by Django 4.0.1 on 2022-02-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop_type', '0004_alter_joptype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joptype',
            name='slug',
            field=models.SlugField(default='ctrw4v10pybhbtjfe6os', verbose_name='Jop Type Slug'),
        ),
    ]
