# Generated by Django 3.1.11 on 2021-07-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0002_auto_20210629_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochures',
            name='attachment',
            field=models.FileField(upload_to='brochures_document', verbose_name='Document Attachment'),
        ),
    ]
