# Generated by Django 3.2.5 on 2021-07-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0002_alter_brochures_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='brochures',
            name='slug',
            field=models.SlugField(default='hv0n6enfmvtujbxivk6c', verbose_name='Brochure Slug'),
        ),
    ]
