# Generated by Django 3.2.4 on 2021-07-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0004_alter_brochures_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='brochures',
            name='image',
            field=models.ImageField(default='', upload_to='brochures_images', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
