# Generated by Django 3.1.11 on 2021-12-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0007_auto_20210921_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='brochures',
            name='arabic_title',
            field=models.CharField(max_length=120, null=True, verbose_name='Document Title (Arabic)'),
        ),
        migrations.AlterField(
            model_name='brochures',
            name='slug',
            field=models.SlugField(default='r9uxodlw7up1azbpavzx', verbose_name='Brochure Slug'),
        ),
    ]
