# Generated by Django 3.1.11 on 2021-12-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0009_auto_20211220_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochures',
            name='slug',
            field=models.SlugField(default='dklcgyrkohg5d9agemna', verbose_name='Brochure Slug'),
        ),
    ]
