# Generated by Django 3.1.11 on 2021-12-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0011_auto_20211220_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochures',
            name='slug',
            field=models.SlugField(default='rzkb7wbxbr7aqjiaepm2', verbose_name='Brochure Slug'),
        ),
    ]
