# Generated by Django 3.2.4 on 2021-07-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20210726_1056'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='city_f',
        # ),
        # migrations.AlterField(
        #     model_name='contactus',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='city',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.city', verbose_name='City'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
    ]
