# Generated by Django 3.2.4 on 2021-07-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_auto_20210726_1110'),
        ('accounts', '0004_auto_20210726_1108'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='city_f',
        # ),
        # migrations.AlterField(
        #     model_name='contactus',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='city',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.city', verbose_name='City'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.RenameField(
        #     model_name='user',
        #     old_name='city_id',
        #     new_name='city',
        # ),
    ]
