# Generated by Django 3.2.4 on 2021-07-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210706_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='working_field',
            field=models.CharField(blank=True, choices=[('Civil Engineering', 'Civil Engineering'), ('Architecture Engineering', 'Architecture Engineering')], max_length=150, null=True, verbose_name='Working Field'),
        ),
    ]
