# Generated by Django 3.2.4 on 2021-07-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_working_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='working_field',
            field=models.CharField(blank=True, choices=[('Civil Engineering', 'Civil Engineering'), ('Chemical Engineering', 'Chemical Engineering')], max_length=150, null=True, verbose_name='Working Field'),
        ),
    ]
