# Generated by Django 3.2.4 on 2021-07-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_auto_20210726_1155'),
        ('accounts', '0009_remove_user_city_id_id'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='contactus',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='city',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.city', verbose_name='City'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
    ]
