# Generated by Django 3.2.4 on 2021-07-27 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0010_auto_20210727_0845'),
        ('accounts', '0011_auto_20210727_0722'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='contactus',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='city',
        #     field=models.ForeignKey(default='ss', on_delete=django.db.models.deletion.CASCADE, to='address.city', verbose_name='City'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='kepjdw', verbose_name='User Slug'),
        ),
    ]
