# Generated by Django 3.1.11 on 2021-07-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[(1, 'Al-Khartoum'), (2, 'Bahry'), (3, 'Om-Durman')], max_length=10, null=True, verbose_name='City List'),
        ),

    ]
