# Generated by Django 3.1.11 on 2021-07-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_user_city'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='user',
        #     old_name='city_f',
        #     new_name='city',
        # ),
    ]
