# Generated by Django 3.2.4 on 2021-08-02 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('working_field', '0001_initial'),
        ('accounts', '0014_auto_20210802_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='working',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='working_field.workingfield', verbose_name='Working'),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='0rkiyj9txo83w8uprkwk', verbose_name='User Slug'),
        ),
    ]
