# Generated by Django 3.1.11 on 2021-07-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210718_1911'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='user',
        #     old_name='city',
        #     new_name='city_f',
        # ),
    ]
