# Generated by Django 3.1.11 on 2021-07-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210718_1913'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='city_f',
        # ),
    ]
