# Generated by Django 3.1.11 on 2021-07-18 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('accounts', '0017_user_city'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='city_f',
        # ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.city', verbose_name='City'),
        ),
    ]
