# Generated by Django 3.1.11 on 2021-07-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_city_state'),
        ('accounts', '0019_auto_20210718_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_f',
            field=models.CharField(blank=True, choices=[(1, 'Al-Khartoum'), (2, 'Bahry'), (3, 'Om-Durman')],
                                   max_length=10, null=True, verbose_name='City List'),

        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.city', verbose_name='City'),
            preserve_default=False,
        ),
    ]
