# Generated by Django 4.0 on 2022-01-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='f4waqi7nlvq6e6kcaj3s', verbose_name='User Slug'),
        ),
    ]
