# Generated by Django 4.0 on 2022-01-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='zuwnxyyxphldtpfggron', verbose_name='User Slug'),
        ),
    ]
