# Generated by Django 3.2.4 on 2021-08-16 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0006_auto_20210815_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsnotification',
            name='group',
        ),
        migrations.RemoveField(
            model_name='smsnotification',
            name='is_multiple',
        ),
        # migrations.AddField(
        #     model_name='smsnotification',
        #     name='status',
        #     field=models.CharField(blank=True, max_length=11, null=True, verbose_name='SMS Status'),
        # ),
        migrations.AlterField(
            model_name='smscontacts',
            name='slug',
            field=models.SlugField(default='ao9xbhjyfljiyjogumwr', verbose_name='Contact Slug'),
        ),
        migrations.AlterField(
            model_name='smsgroups',
            name='slug',
            field=models.SlugField(default='1wd10fyyl88novc97zsv', verbose_name='Group Slug'),
        ),
        migrations.AlterField(
            model_name='smsnotification',
            name='slug',
            field=models.SlugField(default='tfxf9yyuwwhc8rjwiwur', verbose_name='SMS Slug'),
        ),
        migrations.CreateModel(
            name='SMSGroupMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='SMS Message')),
                ('slug', models.SlugField(default='tj0ns0sica0jhmf7kgx7', verbose_name='Contact Slug')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_notifications.smsgroups', verbose_name='SMS Group')),
            ],
        ),
    ]
