# Generated by Django 3.1.11 on 2021-12-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0012_auto_20211220_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscontacts',
            name='slug',
            field=models.SlugField(default='im6bs3s112jrtodhnp0j', verbose_name='Contact Slug'),
        ),
        migrations.AlterField(
            model_name='smsgroupmessages',
            name='slug',
            field=models.SlugField(default='kcjsutfbxtr8vpwzj79z', verbose_name='SMS Group Message Slug'),
        ),
        migrations.AlterField(
            model_name='smsgroups',
            name='slug',
            field=models.SlugField(default='brh8gzcuieg4k3wkck7w', verbose_name='Group Slug'),
        ),
        migrations.AlterField(
            model_name='smsnotification',
            name='slug',
            field=models.SlugField(default='ng4pzsf59spt5mw9zg4a', verbose_name='SMS Slug'),
        ),
    ]
