# Generated by Django 4.0.1 on 2022-02-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0026_smsnotification_status_alter_smscontacts_slug_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='smsnotification',
        #     name='status',
        #     field=models.CharField(blank=True, max_length=11, null=True, verbose_name='SMS Status'),
        # ),
        # migrations.AlterField(
        #     model_name='smscontacts',
        #     name='slug',
        #     field=models.SlugField(default='tikjp7p9nsgazzv1ibpj', verbose_name='Contact Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsgroupmessages',
        #     name='slug',
        #     field=models.SlugField(default='gppweztcmfqgqfgyvyet', verbose_name='SMS Group Message Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsgroups',
        #     name='slug',
        #     field=models.SlugField(default='wlsdbapo1mmny61bgwlj', verbose_name='Group Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsnotification',
        #     name='slug',
        #     field=models.SlugField(default='ewe4crxhxpqrzr1ty1kr', verbose_name='SMS Slug'),
        # ),
    ]
