# Generated by Django 4.0.1 on 2022-02-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0029_smsnotification_status_alter_smscontacts_slug_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='smscontacts',
        #     name='slug',
        #     field=models.SlugField(default='zjvrjehlrofvw4fio6fe', verbose_name='Contact Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsgroupmessages',
        #     name='slug',
        #     field=models.SlugField(default='qyfpkeaczjdcggb0b3hb', verbose_name='SMS Group Message Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsgroups',
        #     name='slug',
        #     field=models.SlugField(default='oxd04hezyrfv5avtrklg', verbose_name='Group Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsnotification',
        #     name='slug',
        #     field=models.SlugField(default='wipold0sw53udbgo5spm', verbose_name='SMS Slug'),
        # ),
    ]
