# Generated by Django 4.0.1 on 2022-02-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0033_smsnotification_status_alter_smscontacts_slug_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='smsnotification',
        #     name='status',
        #     field=models.CharField(blank=True, max_length=11, null=True, verbose_name='SMS Status'),
        # ),
        # migrations.AlterField(
        #     model_name='smscontacts',
        #     name='slug',
        #     field=models.SlugField(default='woivo8lpz0rrrpun8qk5', verbose_name='Contact Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsgroupmessages',
        #     name='slug',
        #     field=models.SlugField(default='5on7wccmb46gvtmgknw1', verbose_name='SMS Group Message Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsgroups',
        #     name='slug',
        #     field=models.SlugField(default='1t64q2rmrnovstdqpxuw', verbose_name='Group Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsnotification',
        #     name='slug',
        #     field=models.SlugField(default='ua7ld8s7kxhkn010efi8', verbose_name='SMS Slug'),
        # ),
    ]
