# Generated by Django 4.0.1 on 2022-02-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0035_smsnotification_status_alter_smscontacts_slug_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='smsnotification',
        #     name='status',
        #     field=models.CharField(blank=True, max_length=11, null=True, verbose_name='SMS Status'),
        # ),
        # migrations.AlterField(
        #     model_name='smscontacts',
        #     name='slug',
        #     field=models.SlugField(default='fudjtdkn8wzx4y7pmrcn', verbose_name='Contact Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsgroupmessages',
        #     name='slug',
        #     field=models.SlugField(default='hmqmmzb2ze3s68gsfoif', verbose_name='SMS Group Message Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsgroups',
        #     name='slug',
        #     field=models.SlugField(default='r2pi6o9hl4pdxgjqra8h', verbose_name='Group Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsnotification',
        #     name='slug',
        #     field=models.SlugField(default='zufrh5a2idxxtl4w8owe', verbose_name='SMS Slug'),
        # ),
    ]
