# Generated by Django 4.0.1 on 2022-02-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0036_smsnotification_status_alter_smscontacts_slug_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='smsnotification',
        #     name='status',
        #     field=models.CharField(blank=True, max_length=11, null=True, verbose_name='SMS Status'),
        # ),
        # migrations.AlterField(
        #     model_name='smscontacts',
        #     name='slug',
        #     field=models.SlugField(default='iv2uqahnniuhe39kqr5f', verbose_name='Contact Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsgroupmessages',
        #     name='slug',
        #     field=models.SlugField(default='clf5md3wlqqbh3baxqq9', verbose_name='SMS Group Message Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsgroups',
        #     name='slug',
        #     field=models.SlugField(default='piyxlertowuh8npxhxh0', verbose_name='Group Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsnotification',
        #     name='slug',
        #     field=models.SlugField(default='rgs7snzk5qlqd4dokfim', verbose_name='SMS Slug'),
        # ),
    ]
