# Generated by Django 4.0.1 on 2022-02-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0039_smsnotification_status_alter_smscontacts_slug_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='smsnotification',
        #     name='status',
        #     field=models.CharField(blank=True, max_length=11, null=True, verbose_name='SMS Status'),
        # ),
        # migrations.AlterField(
        #     model_name='smscontacts',
        #     name='slug',
        #     field=models.SlugField(default='zvjei0i9joxddzvlmxla', verbose_name='Contact Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsgroupmessages',
        #     name='slug',
        #     field=models.SlugField(default='ljkyq8cy0icqszwsltr4', verbose_name='SMS Group Message Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsgroups',
        #     name='slug',
        #     field=models.SlugField(default='sisuhkcl3b63b1ehpufr', verbose_name='Group Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsnotification',
        #     name='slug',
        #     field=models.SlugField(default='pz6yhywpzztwlnpeeaxf', verbose_name='SMS Slug'),
        # ),
    ]
