# Generated by Django 4.0.5 on 2022-06-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0040_smsnotification_status_alter_smscontacts_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscontacts',
            name='slug',
            field=models.SlugField(default='hp3fp7szsb9oglsqtf4s', verbose_name='Contact Slug'),
        ),
        migrations.AlterField(
            model_name='smsgroupmessages',
            name='slug',
            field=models.SlugField(default='3e7qwlttr08qoqnn9mbs', verbose_name='SMS Group Message Slug'),
        ),
        migrations.AlterField(
            model_name='smsgroups',
            name='slug',
            field=models.SlugField(default='xxzeme0qon4nh71drull', verbose_name='Group Slug'),
        ),
        migrations.AlterField(
            model_name='smsnotification',
            name='slug',
            field=models.SlugField(default='brzaok8cxlrbpuuq02xn', verbose_name='SMS Slug'),
        ),
    ]
