# Generated by Django 4.0 on 2022-02-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='approvals_images', verbose_name='Image')),
                ('file', models.FileField(blank=True, null=True, upload_to='brochures_document', verbose_name='File')),
            ],
        ),
    ]
