# Generated by Django 4.0 on 2022-02-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='slug',
            field=models.SlugField(default='gejsxtvfejdmxfu8epjb', verbose_name='Approval Slug'),
        ),
    ]
