# Generated by Django 4.0 on 2022-02-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_approval_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='slug',
            field=models.SlugField(default='huusfboxleqzriuau8n9', unique=True, verbose_name='Approval Slug'),
        ),
    ]
