# Generated by Django 4.0.2 on 2022-02-27 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_alter_approval_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='image',
        ),
        migrations.AlterField(
            model_name='approval',
            name='slug',
            field=models.SlugField(default='9avq6bpjderaxpfszu8b', unique=True, verbose_name='Approval Slug'),
        ),
        migrations.CreateModel(
            name='ApprovalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='dy26dr8ju2umhsiwhyjf', unique=True, verbose_name='Approval Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='approvals_images', verbose_name='Image')),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='approvals.approval', verbose_name='Approval')),
            ],
        ),
    ]
