# Generated by Django 4.0 on 2022-02-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_remove_approval_image_alter_approval_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalimage',
            name='slug',
        ),
        migrations.AlterField(
            model_name='approval',
            name='slug',
            field=models.SlugField(default='ntcrbg9uhapzhylsn51l', unique=True, verbose_name='Approval Slug'),
        ),
    ]
