# Generated by Django 4.0 on 2022-02-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_remove_approvalimage_slug_alter_approval_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='approvals_document', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='slug',
            field=models.SlugField(blank=True, default='0b68ipa3gxs26asnwdkc', null=True, unique=True, verbose_name='Approval Slug'),
        ),
    ]
