# Generated by Django 4.0 on 2022-02-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0006_alter_approval_file_alter_approval_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='slug',
            field=models.SlugField(blank=True, default='nyid9mnr8kffsbfw5yub', null=True, unique=True, verbose_name='Approval Slug'),
        ),
    ]
