# Generated by Django 4.0 on 2022-02-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0007_alter_approval_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='slug',
            field=models.SlugField(blank=True, default='rkwmtiuqvfzt4d9zoasi', null=True, verbose_name='Approval Slug'),
        ),
    ]
