# Generated by Django 4.0.5 on 2022-07-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0009_alter_approval_slug_alter_approvalimage_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='slug',
            field=models.SlugField(blank=True, default='ydxsxoacolophrsccsfv', null=True, verbose_name='Approval Slug'),
        ),
    ]
