# Generated by Django 3.2.4 on 2021-07-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210726_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='eoywty', verbose_name='Project Slug'),
        ),
    ]
