# Generated by Django 3.2.4 on 2021-08-02 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20210730_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.application', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='iddf4t', verbose_name='Project Slug'),
        ),
    ]
