# Generated by Django 3.2.4 on 2021-08-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20210803_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='execution_date',
            field=models.DateField(max_length=200, verbose_name='Execution Year'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='ryr9h1', verbose_name='Project Slug'),
        ),
    ]
