# Generated by Django 3.2.4 on 2021-08-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20210803_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_material',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Main Material Used'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='ni7rhm', verbose_name='Project Slug'),
        ),
    ]
