# Generated by Django 3.2.4 on 2021-08-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20210815_1151'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(default='uzksde', verbose_name='Project Application Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='beneficiary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project Beneficiary'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='0z7pqu', verbose_name='Project Slug'),
        ),
    ]
