# Generated by Django 3.2.4 on 2021-08-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20210815_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='application',
            new_name='project_type',
        ),
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(default='necc7t', verbose_name='Project Application Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='ndobew', verbose_name='Project Slug'),
        ),
    ]
