# Generated by Django 3.1.11 on 2021-09-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_auto_20210921_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', upload_to='default_project_images', verbose_name='Base Project Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(default='8d3p7g', verbose_name='Project Type Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='67a4w3', verbose_name='Project Slug'),
        ),
    ]
