# Generated by Django 3.1.11 on 2021-09-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_auto_20210922_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(default='kkg1ev', verbose_name='Project Type Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='Project Order'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='gfnev2', verbose_name='Project Slug'),
        ),
    ]
