# Generated by Django 3.1.11 on 2021-12-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_auto_20211220_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='arabic_name',
            field=models.CharField(max_length=300, null=True, verbose_name='Project Type(Arabic)'),
        ),
        migrations.AddField(
            model_name='project',
            name='arabic_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Project Name(Arabic)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(default='qqa9ng', verbose_name='Project Type Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='qi3lhe', verbose_name='Project Slug'),
        ),
    ]
