# Generated by Django 4.0.2 on 2022-02-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0063_alter_application_slug_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(default='u5givo', verbose_name='Project Type Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='ixyomh', verbose_name='Project Slug'),
        ),
    ]
