# Generated by Django 3.1.11 on 2021-07-18 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('group_created_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Group Created DateTime')),
            ],
        ),
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=11, verbose_name='SMS Sender')),
                ('message', models.TextField(verbose_name='SMS Message')),
                ('single_mobile_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Single Mobile Number')),
                ('is_multiple', models.BooleanField(verbose_name='Is Message Sent To Many Users?')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_notifications.smsgroups', verbose_name='SMS Group')),
            ],
        ),
        migrations.CreateModel(
            name='SMSContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=18, verbose_name='Contact Number')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_notifications.smsgroups', verbose_name='SMS Group')),
            ],
        ),
    ]
