# Generated by Django 3.2.5 on 2021-08-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0004_auto_20210804_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsnotification',
            name='sender',
        ),
        migrations.AlterField(
            model_name='smscontacts',
            name='slug',
            field=models.SlugField(default='wjsyw0pwbeaypigo7osy', verbose_name='Contact Slug'),
        ),
        migrations.AlterField(
            model_name='smsgroups',
            name='slug',
            field=models.SlugField(default='59butfay7dwadrthhk5z', verbose_name='Group Slug'),
        ),
        migrations.AlterField(
            model_name='smsnotification',
            name='slug',
            field=models.SlugField(default='vlqcltksnlijwuimb8vz', verbose_name='SMS Slug'),
        ),
    ]
