# Generated by Django 3.1.11 on 2021-12-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0011_auto_20211220_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsgroups',
            name='arabic_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Group Name(Arabic)'),
        ),
        migrations.AlterField(
            model_name='smscontacts',
            name='slug',
            field=models.SlugField(default='grruptqa6wet7edodh6u', verbose_name='Contact Slug'),
        ),
        migrations.AlterField(
            model_name='smsgroupmessages',
            name='slug',
            field=models.SlugField(default='i94lmzzwsjm2980uuptv', verbose_name='SMS Group Message Slug'),
        ),
        migrations.AlterField(
            model_name='smsgroups',
            name='slug',
            field=models.SlugField(default='on9x295ars5dttqdaisz', verbose_name='Group Slug'),
        ),
        migrations.AlterField(
            model_name='smsnotification',
            name='slug',
            field=models.SlugField(default='tvxwxknbl5s9fzgzfo5s', verbose_name='SMS Slug'),
        ),
    ]
