# Generated by Django 4.0 on 2022-01-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0020_smsnotification_status_alter_smscontacts_slug_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='smsnotification',
        #     name='status',
        #     field=models.CharField(blank=True, max_length=11, null=True, verbose_name='SMS Status'),
        # ),
        migrations.AlterField(
            model_name='smscontacts',
            name='slug',
            field=models.SlugField(default='demqgimvh66huq7ywyqw', verbose_name='Contact Slug'),
        ),
        migrations.AlterField(
            model_name='smsgroupmessages',
            name='slug',
            field=models.SlugField(default='zuyjmi4vk6b5ttox9lff', verbose_name='SMS Group Message Slug'),
        ),
        migrations.AlterField(
            model_name='smsgroups',
            name='slug',
            field=models.SlugField(default='wuepls5pa7ipmourf5wv', verbose_name='Group Slug'),
        ),
        migrations.AlterField(
            model_name='smsnotification',
            name='slug',
            field=models.SlugField(default='fttbrzccp3revvz0hrqg', verbose_name='SMS Slug'),
        ),
    ]
