# Generated by Django 4.0 on 2022-01-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0023_smsnotification_status_alter_smscontacts_slug_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='smscontacts',
        #     name='slug',
        #     field=models.SlugField(default='ydhorp6xuqpwhuawk1br', verbose_name='Contact Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsgroupmessages',
        #     name='slug',
        #     field=models.SlugField(default='mztjxyusmh1fkgtrhyee', verbose_name='SMS Group Message Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsgroups',
        #     name='slug',
        #     field=models.SlugField(default='jgmyfckue4ob0nfu32t0', verbose_name='Group Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='smsnotification',
        #     name='slug',
        #     field=models.SlugField(default='qedivygflhepaxai1v6d', verbose_name='SMS Slug'),
        # ),
    ]
