# Generated by Django 4.0 on 2022-01-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0024_alter_smscontacts_slug_alter_smsgroupmessages_slug_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='smsnotification',
        #     name='status',
        #     field=models.CharField(blank=True, max_length=11, null=True, verbose_name='SMS Status'),
        # ),
        migrations.AlterField(
            model_name='smscontacts',
            name='slug',
            field=models.SlugField(default='bfafrhqulloliccj5wn7', verbose_name='Contact Slug'),
        ),
        migrations.AlterField(
            model_name='smsgroupmessages',
            name='slug',
            field=models.SlugField(default='j6mxjhfwjefpfbdz8wri', verbose_name='SMS Group Message Slug'),
        ),
        migrations.AlterField(
            model_name='smsgroups',
            name='slug',
            field=models.SlugField(default='xxbnj1o1j4vixmwotjdx', verbose_name='Group Slug'),
        ),
        migrations.AlterField(
            model_name='smsnotification',
            name='slug',
            field=models.SlugField(default='vcrw4k46qgyzm6bmas8z', verbose_name='SMS Slug'),
        ),
    ]
