# Generated by Django 3.2.4 on 2021-08-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('link', models.URLField(verbose_name='Link')),
                ('slug', models.SlugField(default='q5hxt8ojx6mk9xqqyfue', verbose_name='Industry Slug')),
            ],
        ),
    ]
