# Generated by Django 3.2.5 on 2021-08-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryupdates',
            name='details',
            field=models.TextField(default='', verbose_name='Details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industryupdates',
            name='image',
            field=models.ImageField(default='', upload_to='industry_updates_images', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industryupdates',
            name='slug',
            field=models.SlugField(default='plpsidxqq8ciwx6h8r5o', verbose_name='Industry Slug'),
        ),
    ]
