# Generated by Django 3.2.4 on 2021-09-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_updates', '0003_auto_20210902_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industryupdates',
            name='image',
        ),
        migrations.AlterField(
            model_name='industryupdates',
            name='slug',
            field=models.SlugField(default='f8elmttq82yaqvdjbei7', verbose_name='Industry Slug'),
        ),
    ]
