# Generated by Django 3.2.5 on 2021-09-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_updates', '0004_auto_20210902_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryupdates',
            name='source',
            field=models.CharField(default='Uniseal Construction Chemicals Co Ltd', max_length=400, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='industryupdates',
            name='slug',
            field=models.SlugField(default='uyfcbbayl8mpypkoksw6', verbose_name='Industry Slug'),
        ),
    ]
