# Generated by Django 3.2.5 on 2021-09-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_updates', '0006_auto_20210904_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industryupdates',
            old_name='source',
            new_name='link',
        ),
        migrations.AlterField(
            model_name='industryupdates',
            name='slug',
            field=models.SlugField(default='qtb2enslujcaopfx7uw2', verbose_name='Industry Slug'),
        ),
    ]
