# Generated by Django 3.1.11 on 2021-12-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_updates', '0012_auto_20211220_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryupdates',
            name='arabic_details',
            field=models.TextField(blank=True, null=True, verbose_name='Details(Arabic)'),
        ),
        migrations.AlterField(
            model_name='industryupdates',
            name='slug',
            field=models.SlugField(default='rz8pqmc66l3voidxqjgp', verbose_name='Industry Slug'),
        ),
    ]
