# Generated by Django 4.0 on 2022-01-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_updates', '0015_alter_industryupdates_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryupdates',
            name='slug',
            field=models.SlugField(default='xvvfxsvzjr8bovkgwuyo', verbose_name='Industry Slug'),
        ),
    ]
