# Generated by Django 4.0.1 on 2022-02-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_updates', '0032_alter_industryupdates_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryupdates',
            name='slug',
            field=models.SlugField(default='c0r4mp6s469uepkvas5v', verbose_name='Industry Slug'),
        ),
    ]
