# Generated by Django 4.0.1 on 2022-02-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_updates', '0037_alter_industryupdates_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryupdates',
            name='slug',
            field=models.SlugField(default='pmv3kz2x8mjp5inksnkv', verbose_name='Industry Slug'),
        ),
    ]
