# Generated by Django 3.1.11 on 2021-07-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='state',
        # ),
    ]
