# Generated by Django 3.1.11 on 2021-07-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_city_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
    ]
