# Generated by Django 3.1.11 on 2021-07-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_remove_city_country'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='country',
        # ),
    ]
