# Generated by Django 3.2.5 on 2021-07-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0011_auto_20210728_0642'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='country',
        # ),
        migrations.AddField(
            model_name='area',
            name='slug',
            field=models.SlugField(default='zmnaaj', verbose_name='Area Slug'),
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='lvlb3j', verbose_name='City Slug'),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(default='glshui', verbose_name='Country Slug'),
        ),
        migrations.AddField(
            model_name='state',
            name='slug',
            field=models.SlugField(default='nysflv', verbose_name='State Slug'),
        ),
        # migrations.AlterField(
        #     model_name='area',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='city',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='country',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='state',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
    ]
