# Generated by Django 3.2.5 on 2021-07-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0013_auto_20210730_2006'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='country',
        # ),
        # migrations.AlterField(
        #     model_name='area',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(default='tck1isrulh6w1au2bvjb', verbose_name='Area Slug'),
        ),
        # migrations.AlterField(
        #     model_name='city',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='3aqrvwrxjfh5xsregmfd', verbose_name='City Slug'),
        ),
        # migrations.AlterField(
        #     model_name='country',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(default='ejljjaxiyqkd67aqv92m', verbose_name='Country Slug'),
        ),
        # migrations.AlterField(
        #     model_name='state',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(default='oat6xgtxhqd8nsxafq7l', verbose_name='State Slug'),
        ),
    ]
