# Generated by Django 3.2.4 on 2021-08-02 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0014_auto_20210731_0923'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='country',
        # ),
        migrations.AlterField(
            model_name='area',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.city', verbose_name='City'),
        ),
        # migrations.AlterField(
        #     model_name='area',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(default='6knot2zkx1rx65goek8n', verbose_name='Area Slug'),
        ),
        # migrations.AlterField(
        #     model_name='city',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='uimbbcexhd8c8gnmt9nz', verbose_name='City Slug'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.state', verbose_name='State'),
        ),
        # migrations.AlterField(
        #     model_name='country',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(default='gro67opdou4badhrdznd', verbose_name='Country Slug'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.country', verbose_name='Country'),
        ),
        # migrations.AlterField(
        #     model_name='state',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(default='zc6byxbbuia2wk6i476s', verbose_name='State Slug'),
        ),
    ]
