# Generated by Django 3.1.11 on 2021-12-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0020_auto_20211220_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(default='fjyzpoz8nhh3b61pepw0', verbose_name='Area Slug'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='m60wvagumqwgrh87er2b', verbose_name='City Slug'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(default='er0jtpouwpcsvctnqoqg', verbose_name='Country Slug'),
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(default='x1pjgx61gu4kuobdlou6', verbose_name='State Slug'),
        ),
    ]
