# Generated by Django 3.1.11 on 2021-12-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0023_auto_20211220_1120'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='country',
        # ),
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(default='7qh2ycbs0idvgadweyxa', verbose_name='Area Slug'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='q9elti4o09sjw3agqffr', verbose_name='City Slug'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(default='c2les6v1apscngtsvbcn', verbose_name='Country Slug'),
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(default='fghoyv7uplz7imigim5g', verbose_name='State Slug'),
        ),
    ]
