# Generated by Django 3.1.11 on 2021-07-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Supplier Name')),
                ('image', models.ImageField(upload_to='supplier_images/', verbose_name='Supplier Image')),
                ('link', models.URLField(default='', verbose_name='Link')),
            ],
        ),
    ]
