# Generated by Django 3.2.4 on 2021-07-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplier_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(default='thkw3u', verbose_name='Supplier Slug'),
        ),
    ]
