# Generated by Django 4.0 on 2022-01-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0017_alter_supplier_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(default='g8jbadwzwcsmzcoek0os', verbose_name='Supplier Slug'),
        ),
    ]
