# Generated by Django 4.0.1 on 2022-02-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0023_alter_supplier_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(default='3bypsvpfnm8i9evdk8ar', verbose_name='Supplier Slug'),
        ),
    ]
