# Generated by Django 3.2.4 on 2021-09-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_alter_slider_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slug',
            field=models.SlugField(default='6xcz6gpvekyxrq0vwc9x', verbose_name='Slider Slug'),
        ),
    ]
