# Generated by Django 3.1.11 on 2021-12-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0006_auto_20211220_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='arabic_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title(Arabic)'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slug',
            field=models.SlugField(default='wc3lqad2v2ht8gkzzxey', verbose_name='Slider Slug'),
        ),
    ]
