# Generated by Django 3.1.11 on 2021-12-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0009_auto_20211220_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slug',
            field=models.SlugField(default='nefxvk7lxas6s6b8uzpu', verbose_name='Slider Slug'),
        ),
    ]
