# Generated by Django 4.0 on 2022-01-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0011_alter_slider_id_alter_slider_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slug',
            field=models.SlugField(default='okxs33zrpde75tg2lsd8', verbose_name='Slider Slug'),
        ),
    ]
