# Generated by Django 4.0 on 2022-01-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0014_alter_slider_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slug',
            field=models.SlugField(default='qlkyqib8kjxpczpkctzo', verbose_name='Slider Slug'),
        ),
    ]
