# Generated by Django 3.2.5 on 2021-07-31 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0014_auto_20210731_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100, unique=True, verbose_name='Company Primary Phone Number')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Company Email Address')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company Name')),
                ('main_address', models.CharField(max_length=250, verbose_name='Company Main Address')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.city', verbose_name='City')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.country', verbose_name='Country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.state', verbose_name='State')),
            ],
        ),
    ]
