# Generated by Django 3.2.4 on 2021-08-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='slug',
            field=models.SlugField(default='ijv4ribacqhny5klaorh', verbose_name='Company Slug'),
        ),
    ]
