# Generated by Django 3.2.4 on 2021-08-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0004_alter_companyinfo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='marketing_executive_phone_number',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Marketing Executive Phone Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='slug',
            field=models.SlugField(default='ospcypoefjncffhcnamv', verbose_name='Company Slug'),
        ),
    ]
