# Generated by Django 3.1.11 on 2021-12-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0010_auto_20211220_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='arabic_company_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Company Name(Arabic)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='slug',
            field=models.SlugField(default='myppesd739sg6behshu7', verbose_name='Company Slug'),
        ),
    ]
