# Generated by Django 4.0 on 2022-01-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0017_alter_companyinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='slug',
            field=models.SlugField(default='ihp4qcw1gjrdxlgo6idf', verbose_name='Company Slug'),
        ),
    ]
