# Generated by Django 4.0 on 2022-01-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0019_alter_companyinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='slug',
            field=models.SlugField(default='8e1nmbohb5rwdmjviely', verbose_name='Company Slug'),
        ),
    ]
