# Generated by Django 3.2.4 on 2021-08-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingfield',
            name='slug',
            field=models.SlugField(default='pb4fvapmti9f9ycf8eog', verbose_name='Working Field Slug'),
        ),
    ]
