# Generated by Django 3.2.4 on 2021-07-04 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210704_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Added Date'),
        ),
    ]
