# Generated by Django 3.2.4 on 2021-06-29 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Project Name')),
                ('title', models.CharField(max_length=120, verbose_name='Project Title')),
                ('category', models.CharField(max_length=100, verbose_name='Project Category')),
                ('beneficiary', models.CharField(max_length=100, verbose_name='Project Beneficiary')),
                ('image', models.ImageField(upload_to='project_images', verbose_name='Project Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Project Description')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(verbose_name='Project Video Url')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images', verbose_name='Project Image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Project')),
            ],
        ),
    ]
