# Generated by Django 3.2.4 on 2021-07-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='execution_date',
            field=models.DateField(default='2020-7-28', verbose_name='Project Execution Date'),
            preserve_default=False,
        ),
        # migrations.AlterField(
        #     model_name='project',
        #     name='slug',
        #     field=models.SlugField(default='o9d5zn', verbose_name='Project Slug'),
        # ),
    ]
