# Generated by Django 3.2.4 on 2021-07-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210728_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.application', verbose_name='Application'),
            preserve_default=False,
        ),
        # migrations.AlterField(
        #     model_name='project',
        #     name='slug',
        #     field=models.SlugField(default='mkki71', verbose_name='Project Slug'),
        # ),
    ]
