# Generated by Django 3.2.5 on 2021-07-30 09:15

import Util.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210728_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='execution_date',
        ),
        migrations.AddField(
            model_name='project',
            name='execution_year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2000), Util.utils.max_value_current_year], verbose_name='Execution Year'),
        ),
        # migrations.AlterField(
        #     model_name='project',
        #     name='slug',
        #     field=models.SlugField(default='z52kb0', verbose_name='Project Slug'),
        # ),
    ]
