# Generated by Django 3.2.5 on 2021-08-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20210802_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='execution_year',
            new_name='execution_date',
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='zvacio', verbose_name='Project Slug'),
        ),
    ]
