# Generated by Django 3.2.4 on 2021-08-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20210802_2011'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='project',
        #     name='execution_date',
        #     field=models.DateField(verbose_name='Execution Year'),
        # ),
        # migrations.AlterField(
        #     model_name='project',
        #     name='slug',
        #     field=models.SlugField(default='mvt13m', verbose_name='Project Slug'),
        # ),
    ]
