# Generated by Django 3.2.4 on 2021-08-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20210815_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='slug',
            field=models.SlugField(default='7fcmzb', verbose_name='Project Application Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='jrk0kr', verbose_name='Project Slug'),
        ),
    ]
