# Generated by Django 3.2.4 on 2021-08-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20210815_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(default='wfsiqn', verbose_name='Project Application Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='dpoezn', verbose_name='Project Slug'),
        ),
    ]
