# Generated by Django 3.2.4 on 2021-08-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20210817_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimages',
            name='default_image',
            field=models.BooleanField(default=False, verbose_name='Default Image?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(default='paiyv3', verbose_name='Project Type Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='k8i4cp', verbose_name='Project Slug'),
        ),
    ]
