# Generated by Django 3.2.4 on 2021-08-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_auto_20210830_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='execution_date',
        ),
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(default='dpekc0', verbose_name='Project Type Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.CharField(default='', max_length=100, verbose_name='Project Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='nbxrwr', verbose_name='Project Slug'),
        ),
    ]
