# Generated by Django 3.1.11 on 2021-09-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_auto_20210920_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Is Top Project?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(default='n1vx55', verbose_name='Project Type Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='cphsze', verbose_name='Project Slug'),
        ),
    ]
