# Generated by Django 3.1.11 on 2021-09-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_auto_20210922_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimages',
            name='is_default',
        ),
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(default='3cldpe', verbose_name='Project Type Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='a5zh0a', verbose_name='Project Slug'),
        ),
    ]
