# Generated by Django 3.1.11 on 2021-12-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_auto_20211220_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='arabic_description',
            field=models.TextField(blank=True, null=True, verbose_name='Project Description(Arabic)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='arabic_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Project Type(Arabic)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(default='lwquzj', verbose_name='Project Type Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='arabic_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project Name(Arabic)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='ineoj7', verbose_name='Project Slug'),
        ),
    ]
