# Generated by Django 3.2.4 on 2021-07-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(default='bzir3w', verbose_name='User Slug'),
        ),
    ]
