# Generated by Django 3.1.11 on 2021-07-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20210629_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='image',
            field=models.ImageField(upload_to='supplier_images/', verbose_name='Supplier Image'),
        ),
    ]
