# Generated by Django 3.2.4 on 2021-07-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_alter_supplier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='link',
            field=models.URLField(default='', verbose_name='Link'),
        ),
    ]
