# Generated by Django 3.2.4 on 2021-08-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_alter_supplier_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(default='mbrhzf', verbose_name='Supplier Slug'),
        ),
    ]
