# Generated by Django 3.2.4 on 2021-08-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_alter_supplier_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(default='1fa6cpghbkazou8gqutu', verbose_name='Supplier Slug'),
        ),
    ]
