# Generated by Django 4.0 on 2022-01-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0016_alter_supplier_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(default='8suvdxdftiape5tsfgdq', verbose_name='Supplier Slug'),
        ),
    ]
