# Generated by Django 4.0 on 2022-02-14 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_user_slug'),
        ('request_permissions', '0002_alter_requestaccess_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestaccess',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user', verbose_name='User'),
            preserve_default=False,
        ),
    ]
