# Generated by Django 4.0.1 on 2022-02-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0035_remove_city_country_alter_area_id_alter_area_slug_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='country',
        # ),
        # migrations.AlterField(
        #     model_name='area',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='area',
        #     name='slug',
        #     field=models.SlugField(default='cbf3clkuw9oyc1uuoxgy', verbose_name='Area Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='city',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='city',
        #     name='slug',
        #     field=models.SlugField(default='4lvnonxoni6ydra2clb3', verbose_name='City Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='country',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='country',
        #     name='slug',
        #     field=models.SlugField(default='vqazxzqr1364e8smnr43', verbose_name='Country Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='state',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='state',
        #     name='slug',
        #     field=models.SlugField(default='ykiapkblhpf62erweu7p', verbose_name='State Slug'),
        # ),
    ]
