# Generated by Django 4.0.1 on 2022-02-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0038_remove_city_country_alter_area_id_alter_area_slug_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='area',
        #     name='slug',
        #     field=models.SlugField(default='vpx6vzxaevcayukjarsg', verbose_name='Area Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='city',
        #     name='slug',
        #     field=models.SlugField(default='dluginw4prvr5ta0h9pn', verbose_name='City Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='country',
        #     name='slug',
        #     field=models.SlugField(default='drujckhregbl629gsrsl', verbose_name='Country Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='state',
        #     name='slug',
        #     field=models.SlugField(default='1jrkqj1lek1dmbl788hd', verbose_name='State Slug'),
        # ),
    ]
