# Generated by Django 4.0.1 on 2022-02-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0041_remove_city_country_alter_area_id_alter_area_slug_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='country',
        # ),
        # migrations.AlterField(
        #     model_name='area',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='area',
        #     name='slug',
        #     field=models.SlugField(default='awtqmq1igepritkwuugo', verbose_name='Area Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='city',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='city',
        #     name='slug',
        #     field=models.SlugField(default='pxpt7cop8bvrg1jpla2m', verbose_name='City Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='country',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='country',
        #     name='slug',
        #     field=models.SlugField(default='tba4rkvyardvh4ww9j2z', verbose_name='Country Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='state',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='state',
        #     name='slug',
        #     field=models.SlugField(default='zlzlnwon0posumdedmlf', verbose_name='State Slug'),
        # ),
    ]
