# Generated by Django 4.0.1 on 2022-02-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0042_remove_city_country_alter_area_id_alter_area_slug_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='country',
        # ),
        # migrations.AlterField(
        #     model_name='area',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='area',
        #     name='slug',
        #     field=models.SlugField(default='x0u0w1lqh4jh2kcuoquh', verbose_name='Area Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='city',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='city',
        #     name='slug',
        #     field=models.SlugField(default='ghixfmqy5lfs5bzudibq', verbose_name='City Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='country',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='country',
        #     name='slug',
        #     field=models.SlugField(default='5totgrbiuiudlglzfa0q', verbose_name='Country Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='state',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='state',
        #     name='slug',
        #     field=models.SlugField(default='9joban2ls5qabitf0ngp', verbose_name='State Slug'),
        # ),
    ]
