# Generated by Django 4.0.1 on 2022-02-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0045_remove_city_country_alter_area_id_alter_area_slug_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='country',
        # ),
        # migrations.AlterField(
        #     model_name='area',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='area',
        #     name='slug',
        #     field=models.SlugField(default='ebggvccoiz97qlijlulk', verbose_name='Area Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='city',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='city',
        #     name='slug',
        #     field=models.SlugField(default='usdrsjd7zxpva85ycbob', verbose_name='City Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='country',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='country',
        #     name='slug',
        #     field=models.SlugField(default='7rky6pganjbniym8ulin', verbose_name='Country Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='state',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='state',
        #     name='slug',
        #     field=models.SlugField(default='lhsoakd4ytmmbke2rv6e', verbose_name='State Slug'),
        # ),
    ]
