# Generated by Django 4.0.5 on 2022-07-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0049_remove_city_country_alter_area_id_alter_area_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.AlterField(
            model_name='area',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(default='wqvlf8imnjaypthlei8j', verbose_name='Area Slug'),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='vwx9dqnhtagtlvapfkx4', verbose_name='City Slug'),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(default='ned2oaaqpwdtk5xbi00n', verbose_name='Country Slug'),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(default='zewzkidxrf2sp8d9gkgy', verbose_name='State Slug'),
        ),
    ]
