# Generated by Django 3.2.5 on 2021-08-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0004_alter_brochures_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brochures',
            name='image',
        ),
        migrations.AlterField(
            model_name='brochures',
            name='slug',
            field=models.SlugField(default='t3lyp8hlk18i79vgljy1', verbose_name='Brochure Slug'),
        ),
    ]
