# Generated by Django 3.2.5 on 2021-08-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0005_auto_20210817_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='brochures',
            name='image',
            field=models.ImageField(default='', upload_to='brochures_images', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brochures',
            name='slug',
            field=models.SlugField(default='ipkfxrnqnhlmhm17lswg', verbose_name='Brochure Slug'),
        ),
    ]
