# Generated by Django 3.1.11 on 2021-12-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0008_auto_20211220_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochures',
            name='slug',
            field=models.SlugField(default='g2ora8rmyvf7iof8e18s', verbose_name='Brochure Slug'),
        ),
    ]
