# Generated by Django 3.1.11 on 2021-12-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0010_auto_20211220_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochures',
            name='arabic_title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Document Title (Arabic)'),
        ),
        migrations.AlterField(
            model_name='brochures',
            name='slug',
            field=models.SlugField(default='m2vllauprwn57hjgd1gs', verbose_name='Brochure Slug'),
        ),
    ]
