# Generated by Django 4.0 on 2022-01-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0013_alter_brochures_id_alter_brochures_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochures',
            name='slug',
            field=models.SlugField(default='vnbrslsnz3x3ndfhdnww', verbose_name='Brochure Slug'),
        ),
    ]
