# Generated by Django 4.0.1 on 2022-02-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0034_alter_brochures_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochures',
            name='slug',
            field=models.SlugField(default='3mmc2xfijbx2kv5ubsyo', verbose_name='Brochure Slug'),
        ),
    ]
