# Generated by Django 4.0.2 on 2022-02-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0038_alter_brochures_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochures',
            name='slug',
            field=models.SlugField(default='me8ng92sgvqclwjodnyj', verbose_name='Brochure Slug'),
        ),
    ]
