# Generated by Django 4.0 on 2022-02-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_manageproductspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageproducts',
            name='product_sheet_downloads',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Product Sheet Downloads'),
        ),
        migrations.AlterField(
            model_name='manageproducts',
            name='product_views',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Product Views'),
        ),
    ]
