# Generated by Django 4.0 on 2022-02-10 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_order_slug'),
        ('accounts', '0052_alter_user_slug'),
        ('sellingPoint', '0038_alter_sellingpoint_slug'),
        ('solution', '0006_alter_solution_id_alter_solutionimages_id_and_more'),
        ('brochures', '0038_alter_brochures_slug'),
        ('project', '0063_alter_application_slug_alter_project_slug'),
        ('product', '0061_alter_product_slug'),
        ('admin_panel', '0009_alter_manageproducts_product_sheet_downloads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managebrochures',
            name='brochures',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='brochures.brochures', verbose_name='Brochure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managebrochures',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user', verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managecarts',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.cart', verbose_name='Carts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managecarts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user', verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manageproducts',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manageproducts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user', verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manageproductspage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user', verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manageprojects',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='project.project', verbose_name='Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manageprojects',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user', verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managesellingpoints',
            name='selling_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sellingPoint.sellingpoint', verbose_name='Selling Point'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managesellingpoints',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user', verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managesolution',
            name='solution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='solution.solution', verbose_name='Soltion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managesolution',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user', verbose_name='User'),
            preserve_default=False,
        ),
    ]
