# Generated by Django 4.0 on 2022-02-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_alter_managebrochures_brochures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managebrochures',
            name='brochures_sheet_downloads',
            field=models.PositiveIntegerField(default=0, verbose_name='Brochures Sheet Downloads'),
        ),
        migrations.AlterField(
            model_name='managebrochures',
            name='brochures_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Brochures_views'),
        ),
        migrations.AlterField(
            model_name='managecarts',
            name='add_to_cart_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Add To Cart Views'),
        ),
        migrations.AlterField(
            model_name='manageproducts',
            name='product_sheet_downloads',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Product Sheet Downloads'),
        ),
        migrations.AlterField(
            model_name='manageproducts',
            name='product_views',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Product Views'),
        ),
        migrations.AlterField(
            model_name='manageproductspage',
            name='product_page_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Product Page Views'),
        ),
        migrations.AlterField(
            model_name='manageprojects',
            name='project_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Project Views'),
        ),
        migrations.AlterField(
            model_name='managesellingpoints',
            name='phone_number_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='Phone Number Clicks'),
        ),
        migrations.AlterField(
            model_name='managesellingpoints',
            name='secondary_phone_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Secondary Phone Number Clicks'),
        ),
        migrations.AlterField(
            model_name='managesolution',
            name='solution_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Solution Views'),
        ),
    ]
