# Generated by Django 4.0.2 on 2022-02-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_alter_manageproducts_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managecarts',
            name='add_to_cart_views',
        ),
        migrations.AddField(
            model_name='manageproducts',
            name='add_to_cart_views',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Count of add to cart'),
        ),
    ]
