# Generated by Django 4.0.2 on 2022-02-13 07:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0039_alter_brochures_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0064_alter_application_slug_alter_project_slug'),
        ('orders', '0027_alter_order_slug'),
        ('product', '0067_alter_product_slug'),
        ('solution', '0006_alter_solution_id_alter_solutionimages_id_and_more'),
        ('sellingPoint', '0039_alter_sellingpoint_slug'),
        ('admin_panel', '0014_remove_managecarts_add_to_cart_views_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='managebrochures',
            unique_together={('user', 'brochures')},
        ),
        migrations.AlterUniqueTogether(
            name='managecarts',
            unique_together={('order', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='manageproducts',
            unique_together={('product', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='manageprojects',
            unique_together={('project', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='managesellingpoints',
            unique_together={('user', 'selling_point')},
        ),
        migrations.AlterUniqueTogether(
            name='managesolution',
            unique_together={('solution', 'user')},
        ),
    ]
