# Generated by Django 4.0.2 on 2022-02-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_manageproductspage_visit_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageproductspage',
            name='visit_date_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
