# Generated by Django 4.0 on 2022-02-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_managecarts_is_order_paced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managecarts',
            old_name='is_order_paced',
            new_name='is_order_placed',
        ),
    ]
