# Generated by Django 3.2.4 on 2021-06-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Sale Point Name')),
                ('image', models.ImageField(upload_to='sale_point_image', verbose_name='Sale Point Image')),
                ('location', models.CharField(max_length=200, verbose_name='Sale Point Location')),
                ('address', models.CharField(max_length=250, verbose_name='Sale Point Address')),
                ('city', models.CharField(choices=[('Al-Khartoum', 'Al-Khartoum'), ('Bahry', 'Bahry'), ('Om-Durman', 'Om-Durman')], default=1, max_length=350, verbose_name='City')),
                ('area', models.CharField(choices=[('Om-Baddah', 'om-baddah'), ('Al-Saffyah', 'Al-Saffyah'), ('Hay Alarab', 'Hay Alarab'), ('Wad Nubawi', 'Wad Nubawi'), ('Al Mawrada', 'Al Mawrada'), ('Hay Al-Omda', 'Hay Al-Omda'), ('Al Mohandsin', 'Al Mohandsin'), ('Al Molazmin', 'Al Molazmin'), ('Al Arda', 'Al Arda'), ('Banat gharb', 'Banat gharb'), ('Al Hashmab', 'Al Hashmab'), ('Banat sharg', 'Banat sharg'), ('Hai Al nakhiel', 'Hai Al nakhiel'), ('Emtidad bait Al mal', 'Emtidad bait Al mal'), ('Al Sharfiya', 'Al Sharfiya'), ('Al Jarrafa', 'Al Jarrafa'), ('Al Thawra', 'Al Thawra'), ('Abu Roof', 'Abu Roof'), ('Wd Abu Halima', 'Wd Abu Halima'), ('Hay Al-umara Gharb', 'Hay Al-umara Gharb'), ('Bait Al Mal', 'Bait Al Mal'), ('Al Waaha', 'Al Waaha'), ('AL Kabajab', 'AL Kabajab'), ('Hay Al Bosta', 'Hay Al Bosta'), ('Hay Al Mostashfa', 'Hay Al Mostashfa'), ('Al Riyadh', 'Al Riyadh'), ('Al Msalmaa', 'Al Msalmaa'), ('Hay Al-Umara East', 'Hay Al-Umara East'), ('Al Dawha', 'Al Dawha'), ('Sug Al khalifa', 'Sug Al khalifa'), ('Om Bada', 'Om Bada'), ('Alamlaak', 'Alamlaak'), ('Cooper', 'Cooper'), ('Kafouri', 'Kafouri'), ('Bahri Industrial Area', 'Bahri Industrial Area'), ('Al Haj Yousif', 'Al Haj Yousif'), ('Al Sababi', 'Al Sababi'), ('Al Dnagla North', 'Al Dnagla North'), ('Al Dnagla South', 'Al Dnagla South'), ('Hilat Hamad', 'Hilat Hamad'), ('Hilat Khojali', 'Hilat Khojali'), ('Hilat Koko', 'Hilat Koko'), ('Alshabia North', 'Alshabia North'), ('Alshabia South', 'Alshabia South'), ('Almazad', 'Almazad'), ('Almugtaribin', 'Almugtaribin'), ('Almerghania', 'Almerghania'), ('Alsafia', 'Alsafia'), ('Shambat', 'Shambat'), ('AlKhoglab', 'AlKhoglab'), ('Alqadisia', 'Alqadisia'), ('Alhalfaya', 'Alhalfaya'), ('Dardoog', 'Dardoog'), ('Aldroshab', 'Aldroshab'), ('Alkadaro', 'Alkadaro'), ('Alezba', 'Alezba'), ('Alfaki Hashim', 'Alfaki Hashim'), ('Al Gayli', 'Al Gayli'), ('Al Riyadh', 'Al Riyadh'), ('Alamarat', 'Alamarat'), ('Khartoum2', 'Khartoum2'), ('Al-Hilla Al-Jadida', 'Al-Hilla Al-Jadida'), ('Al Diyum East', 'Al Diyum East'), ('khartoum3', 'khartoum3'), ('Burri Almahas', 'Burri Almahas'), ('Nasir Extension', 'Nasir Extension'), ('Al-LaMap', 'Al-LaMap'), ('Burri Al Daraisa', 'Burri Al Daraisa'), ('Burri Alsharif', 'Burri Alsharif'), ('Taha Elmahi', 'Taha Elmahi'), ('Al-Emtidad', 'Al-Emtidad'), ('Saria Residence', 'Saria Residence'), ('Al-Aushara', 'Al-Aushara'), ('Wad-Ageeb', 'Wad-Ageeb'), ('Kalakla Wad Amara', 'Kalakla Wad Amara'), ('Al Diyum West', 'Al Diyum West'), ('Alfirdous East', 'Alfirdous East'), ('Jabra Sharga', 'Jabra Sharga'), ('Al-Jerif West Al-Galaa', 'Al-Jerif West Al-Galaa'), ('Umm Haraz', 'Umm Haraz'), ('Nuzha', 'Nuzha'), ('Wad Husayn', 'Wad Husayn'), ('Al Zohur', 'Al Zohur'), ('Gabra 18', 'Gabra 18'), ('Burri Al Lamab', 'Burri Al Lamab'), ('Abu Dawm', 'Abu Dawm'), ('Garden City', 'Garden City'), ('Gabra 19', 'Gabra 19'), ('Gabra 15', 'Gabra 15'), ('Gabra AlDawha', 'Gabra AlDawha'), ('Gabra 10', 'Gabra 10'), ('Gabra 9', 'Gabra 9')], default=1, max_length=300, verbose_name='Area')),
                ('phone_number', models.CharField(max_length=100, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='SellingPointsContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_phone', models.CharField(max_length=20, verbose_name='Sale Point Primary Phone')),
                ('secondary_phone', models.CharField(max_length=20, verbose_name='Sale Point Secondary Phone')),
            ],
        ),
    ]
