# Generated by Django 3.1.11 on 2021-07-18 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Product Image')),
                ('product_file', models.FileField(blank=True, null=True, upload_to='product_files/', verbose_name='Product File')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('added_date', models.DateField(auto_now=True, verbose_name='Added Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Product Category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier', verbose_name='Supplier Name')),
            ],
        ),
        migrations.CreateModel(
            name='SellingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Sale Point Name')),
                ('image', models.ImageField(upload_to='sale_point_image', verbose_name='Sale Point Image')),
                ('location', models.CharField(max_length=200, verbose_name='Sale Point Location')),
                ('address', models.CharField(max_length=250, verbose_name='Sale Point Address')),
                ('phone_number', models.CharField(max_length=100, unique=True, verbose_name='Phone Number')),
                ('secondary_phone', models.CharField(default='', max_length=20, verbose_name='Sale Point Secondary Phone')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='SimilarProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellingPoint.product', verbose_name='Original Product')),
                ('similar_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_product', to='sellingPoint.product', verbose_name='Similar Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(verbose_name='Product Video Url')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellingPoint.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='Product Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellingPoint.product', verbose_name='Product')),
            ],
        ),
    ]
