# Generated by Django 3.2.4 on 2021-06-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingPoint', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellingPointsContactInfo',
        ),
        migrations.AddField(
            model_name='sellingpoint',
            name='secondary_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Sale Point Secondary Phone'),
            preserve_default=False,
        ),
    ]
