# Generated by Django 3.2.4 on 2021-07-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20210726_1100'),
        ('sellingPoint', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='productimages',
        #     name='product',
        # ),
        # migrations.RemoveField(
        #     model_name='productvideos',
        #     name='product',
        # ),
        # migrations.RemoveField(
        #     model_name='similarproduct',
        #     name='original_product',
        # ),
        # migrations.RemoveField(
        #     model_name='similarproduct',
        #     name='similar_product',
        # ),
        # migrations.AddField(
        #     model_name='sellingpoint',
        #     name='area',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.area'),
        # ),
        # migrations.AddField(
        #     model_name='sellingpoint',
        #     name='city',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.city'),
        # ),
        # migrations.AddField(
        #     model_name='sellingpoint',
        #     name='country',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.country'),
        # ),
        # migrations.AddField(
        #     model_name='sellingpoint',
        #     name='state',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.state'),
        # ),
        # migrations.AlterField(
        #     model_name='sellingpoint',
        #     name='email',
        #     field=models.EmailField(default='ss', max_length=255, unique=True, verbose_name='Email Address'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='sellingpoint',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.DeleteModel(
        #     name='Product',
        # ),
        # migrations.DeleteModel(
        #     name='ProductImages',
        # ),
        # migrations.DeleteModel(
        #     name='ProductVideos',
        # ),
        # migrations.DeleteModel(
        #     name='SimilarProduct',
        # ),
    ]
