# Generated by Django 3.1.6 on 2021-06-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingPoint', '0002_auto_20210629_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingpoint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
