# Generated by Django 3.1.11 on 2021-07-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellingPoint', '0002_auto_20210718_2100'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='sellingpoint',
        #     name='area',
        # ),
    ]
