# Generated by Django 3.1.11 on 2021-07-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingPoint', '0005_auto_20210715_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingpoint',
            name='city',
            field=models.CharField(choices=[(1, 'Al-Khartoum'), (2, 'Bahry'), (3, 'Om-Durman')], default=1, max_length=350, verbose_name='City'),
        ),
    ]
