# Generated by Django 3.1.11 on 2021-07-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_remove_city_country'),
        ('sellingPoint', '0005_auto_20210721_0825'),
    ]

    operations = [

        migrations.AlterField(
            model_name='sellingpoint',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=255, unique=True, verbose_name='Email Address'),
            preserve_default=False,
        ),

    ]
