# Generated by Django 3.1.11 on 2021-12-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingPoint', '0007_auto_20210815_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvideos',
            name='product',
        ),
        migrations.RemoveField(
            model_name='similarproduct',
            name='original_product',
        ),
        migrations.RemoveField(
            model_name='similarproduct',
            name='similar_product',
        ),
        migrations.AlterField(
            model_name='sellingpoint',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellingpoint',
            name='slug',
            field=models.SlugField(default='h26bwydwdaowf4shjivf', verbose_name='Selling Point Slug'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
        migrations.DeleteModel(
            name='ProductVideos',
        ),
        migrations.DeleteModel(
            name='SimilarProduct',
        ),
    ]
