# Generated by Django 4.0 on 2022-01-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_slug'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='order',
        #     name='slug',
        #     field=models.SlugField(default='order-8eq1sa0ara6', verbose_name='Token Slug'),
        # ),
    ]
