# Generated by Django 4.0.1 on 2022-02-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('offer_created_date', models.DateTimeField(auto_now=True, null=True)),
                ('offer_start_date', models.DateField(blank=True, null=True)),
                ('offer_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
