# Generated by Django 4.0.2 on 2022-02-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_alter_offer_image_alter_offer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active Offer?'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(default='d8stbrcznmqnf3pvx2dj', verbose_name='Offer Slug'),
        ),
    ]
