# Generated by Django 4.0 on 2022-02-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_offer_is_active_alter_offer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, default='cmed7zq3kdqqfq6w2zl2', null=True, verbose_name='Offer Slug'),
        ),
    ]
