# Generated by Django 4.0.5 on 2022-07-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_alter_offer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, default='hwovev96efvmswikiwuy', null=True, verbose_name='Offer Slug'),
        ),
    ]
