# Generated by Django 3.1.11 on 2021-09-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.CharField(max_length=800, verbose_name='Device Token')),
                ('slug', models.SlugField(default='klyri1w6lrhcbxc7kefo', verbose_name='Product Slug')),
                ('os_type', models.CharField(max_length=150, verbose_name='OS Type')),
            ],
        ),
    ]
