# Generated by Django 3.1.11 on 2021-09-10 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210910_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenids',
            name='slug',
            field=models.SlugField(default='pfobwrc20hnns040lkwj', verbose_name='Product Slug'),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Notification Title')),
                ('body', models.CharField(max_length=400, verbose_name='Notification Body')),
                ('notification_sending_date', models.DateField(auto_now_add=True, null=True)),
                ('token_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.tokenids', verbose_name='Token ID')),
            ],
        ),
    ]
