# Generated by Django 3.1.11 on 2021-09-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210910_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='slug',
            field=models.SlugField(default='djxthvyoc3dh2pwlqll6', verbose_name='Notification Slug'),
        ),
        migrations.AlterField(
            model_name='tokenids',
            name='slug',
            field=models.SlugField(default='wandrj5zvwfoedalcxrt', verbose_name='Token Slug'),
        ),
    ]
