# Generated by Django 3.1.11 on 2021-09-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20210912_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='slug',
            field=models.SlugField(default='bak4x8ybuztdw00vc3an', verbose_name='Notification Slug'),
        ),
        migrations.AlterField(
            model_name='tokenids',
            name='slug',
            field=models.SlugField(default='inut9tj1ixtzqb7ivne3', verbose_name='Token Slug'),
        ),
    ]
