# Generated by Django 3.2.4 on 2021-08-02 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0016_auto_20210802_0812'),
        ('company_info', '0002_companyinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='slug',
            field=models.SlugField(default='mraliovlkypattbnhvqy', verbose_name='Company Slug'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.state', verbose_name='State'),
        ),
    ]
