# Generated by Django 3.2.4 on 2021-08-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0003_auto_20210802_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='slug',
            field=models.SlugField(default='edmklxe4yyzos1x3ivhd', verbose_name='Company Slug'),
        ),
    ]
