# Generated by Django 3.1.11 on 2021-12-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0006_auto_20210905_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='slug',
            field=models.SlugField(default='u2u4ecapvmdlsnjmgnbo', verbose_name='Company Slug'),
        ),
    ]
