# Generated by Django 3.1.11 on 2021-12-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0007_auto_20211220_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='arabic_company_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Company Name(Arabic)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='slug',
            field=models.SlugField(default='an3xqu1phlhb1dxdftho', verbose_name='Company Slug'),
        ),
    ]
