# Generated by Django 3.1.11 on 2021-12-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0008_auto_20211220_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='slug',
            field=models.SlugField(default='cukqywtwy9wjjxxmclxp', verbose_name='Company Slug'),
        ),
    ]
