# Generated by Django 4.0 on 2022-01-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0012_alter_companyinfo_id_alter_companyinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='slug',
            field=models.SlugField(default='z5j0dbdpaozh6hvqvtop', verbose_name='Company Slug'),
        ),
    ]
