# Generated by Django 4.0.1 on 2022-02-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0025_alter_companyinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='slug',
            field=models.SlugField(default='dldr8ht5f8itqq2jpsa7', verbose_name='Company Slug'),
        ),
    ]
