# Generated by Django 4.0.1 on 2022-02-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0028_alter_companyinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='slug',
            field=models.SlugField(default='42blcqgc9o168wdophuq', verbose_name='Company Slug'),
        ),
    ]
