# Generated by Django 4.0.1 on 2022-02-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0031_alter_companyinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='slug',
            field=models.SlugField(default='rkzzqyei2o9nsiffcocq', verbose_name='Company Slug'),
        ),
    ]
