# Generated by Django 3.1.11 on 2021-09-12 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20210912_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='slug',
            field=models.SlugField(default='urgooxlp1joj9dcfbwir', verbose_name='Notification Slug'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='token_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.tokenids', verbose_name='Token ID'),
        ),
        migrations.AlterField(
            model_name='tokenids',
            name='slug',
            field=models.SlugField(default='4n1z7g1iuhj2raf4j6fj', verbose_name='Token Slug'),
        ),
    ]
