# Generated by Django 3.1.11 on 2021-12-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_auto_20211220_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='arabic_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Notification Title(Arabic)'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='slug',
            field=models.SlugField(default='3byiuz89gqldc6r1inn3', verbose_name='Notification Slug'),
        ),
        migrations.AlterField(
            model_name='tokenids',
            name='slug',
            field=models.SlugField(default='6hp02tkaaaseofoutky9', verbose_name='Token Slug'),
        ),
    ]
