# Generated by Django 4.0.1 on 2022-02-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0027_alter_notifications_slug_alter_tokenids_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='slug',
            field=models.SlugField(default='st83nuacbizspjcwajqp', verbose_name='Notification Slug'),
        ),
        migrations.AlterField(
            model_name='tokenids',
            name='slug',
            field=models.SlugField(default='yz505bhlh8agj2anjpil', verbose_name='Token Slug'),
        ),
    ]
