# Generated by Django 4.0.1 on 2022-02-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0034_alter_notifications_slug_alter_tokenids_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='slug',
            field=models.SlugField(default='5lbb9jicyi0jvom8fgmk', verbose_name='Notification Slug'),
        ),
        migrations.AlterField(
            model_name='tokenids',
            name='slug',
            field=models.SlugField(default='hbjttkhzas3dsrrl5cmy', verbose_name='Token Slug'),
        ),
    ]
