# Generated by Django 4.0.1 on 2022-02-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0035_alter_notifications_slug_alter_tokenids_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='slug',
            field=models.SlugField(default='wvzotp8on5j7rkkrion0', verbose_name='Notification Slug'),
        ),
        migrations.AlterField(
            model_name='tokenids',
            name='slug',
            field=models.SlugField(default='zbnx3gel0lc7vctj6o8i', verbose_name='Token Slug'),
        ),
    ]
