# Generated by Django 4.0.5 on 2022-06-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0037_alter_notifications_slug_alter_tokenids_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='slug',
            field=models.SlugField(default='sekjhksud53voybzu6be', verbose_name='Notification Slug'),
        ),
        migrations.AlterField(
            model_name='tokenids',
            name='reg_id',
            field=models.CharField(max_length=1500, verbose_name='Device Token'),
        ),
        migrations.AlterField(
            model_name='tokenids',
            name='slug',
            field=models.SlugField(default='3bqldf83afn55s6lzjlk', verbose_name='Token Slug'),
        ),
    ]
