# Generated by Django 4.0.5 on 2022-06-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0038_alter_notifications_slug_alter_tokenids_reg_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenids',
            name='reg',
            field=models.TextField(default='', verbose_name='Device Token'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifications',
            name='slug',
            field=models.SlugField(default='oaa49pez0tleoizskjrk', verbose_name='Notification Slug'),
        ),
        migrations.AlterField(
            model_name='tokenids',
            name='slug',
            field=models.SlugField(default='m5ej7wugsvm1plmcivxo', verbose_name='Token Slug'),
        ),
    ]
