# Generated by Django 4.0.5 on 2022-06-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0039_tokenids_reg_alter_notifications_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='slug',
            field=models.SlugField(default='xnot20tgbnrklmvakf9a', verbose_name='Notification Slug'),
        ),
        migrations.AlterField(
            model_name='tokenids',
            name='reg_id',
            field=models.TextField(verbose_name='Device Token'),
        ),
        migrations.AlterField(
            model_name='tokenids',
            name='slug',
            field=models.SlugField(default='uo4mikyc10j9zkgtko8h', verbose_name='Token Slug'),
        ),
    ]
