# Generated by Django 4.0.5 on 2022-06-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0040_alter_notifications_slug_alter_tokenids_reg_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenids',
            name='reg',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='slug',
            field=models.SlugField(default='ixifh7nvx3bwhdrof9di', verbose_name='Notification Slug'),
        ),
        migrations.AlterField(
            model_name='tokenids',
            name='slug',
            field=models.SlugField(default='zz8c0b149q2zvqgwzq6p', verbose_name='Token Slug'),
        ),
    ]
