# Generated by Django 4.0.5 on 2022-07-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0041_remove_tokenids_reg_alter_notifications_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='slug',
            field=models.SlugField(default='davwpj4q7sca1jtqrnms', verbose_name='Notification Slug'),
        ),
        migrations.AlterField(
            model_name='tokenids',
            name='slug',
            field=models.SlugField(default='3d5lqfetwiuyeoivssgg', verbose_name='Token Slug'),
        ),
    ]
