# Generated by Django 3.1.11 on 2021-12-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0005_auto_20210902_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slug',
            field=models.SlugField(default='klnk3fn00n97hmpztuit', verbose_name='Slider Slug'),
        ),
    ]
