# Generated by Django 4.0 on 2022-01-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0015_alter_slider_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slug',
            field=models.SlugField(default='ge4qiods7bbv9nizamjx', verbose_name='Slider Slug'),
        ),
    ]
