# Generated by Django 4.0 on 2022-01-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0017_alter_slider_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slug',
            field=models.SlugField(default='elza8jz6jh0po7xfabmh', verbose_name='Slider Slug'),
        ),
    ]
