# Generated by Django 4.0 on 2022-01-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0020_alter_slider_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slug',
            field=models.SlugField(default='t6ush3p1haluzvorutmp', verbose_name='Slider Slug'),
        ),
    ]
